import sys
import os
from sys import platform as _platform

def root_path():
    path = sys.executable
    listPath = path.split("/")
    #windows default
    splitIndex = 1
    if _platform == "darwin":
        splitIndex = 5
    listPath = listPath[:-splitIndex]
    return "/".join(listPath)

#ROOT_FOLDER = "/Users/neocfc/Documents/LatestApp/Mac"
ROOT_FOLDER = root_path()
MAX_PREVIOUS_DAYS = 15
GRAPH_DIR = "Graph"
DICTIONARY_DIR = "Dictionary"
TEXTCORPUS_DIR = "TEXTCORPUS_DIR"
LDA_DIR = "LDA_DIR"
DICTIONARY_FILE = "graph.dict"
TEXTCORPUS_FILE = "textcorpus.file"
LDA_FILE = "lda.file"
GRAPH_FILE = "graph.gexf"
LOG_DIR = "Log"
LOG_FILE = "graph_log.txt"
NEDREAD = "NeoRedPrediction"
date_LAST_GRAPH_DONE = "date_LAST_GRAPH_DONE"
date_LAST_DICTIONARY_DONE = "date_LAST_DICTIONARY_DONE"
date_LAST_TEXTCORPUS_DONE = "date_LAST_TEXTCORPUS_DONE"
date_LAST_LDA_DONE = "date_LAST_LDA_DONE"
date_LAST_GRAPHNER_DONE = "date_LAST_GRAPHNER_DONE"
date_LAST_DICTIONARYNER_DONE = "date_LAST_DICTIONARYNER_DONE"
date_LAST_TEXTCORPUSNER_DONE = "date_LAST_TEXTCORPUSNER_DONE"
date_LAST_LDANER_DONE = "date_LAST_LDANER_DONE"
FACEBOOK_DIR = "facebookDir"
TWITTER_DIR = "twitterDir"
BOILER_DATA_DIR = "Boiler_Data_Dir"
DICTIONARY_MAXLEN = 2000000
DATA_DIR = "dataDir"
FACEBOOK_DIR = "facebookDir"
TWITTER_DIR = "twitterDir"
ENGINE_DIR = "engineDir"
RELEVANCE_FILE = "relevance.json"
SMOOTHNESS_FILE = "smoothness.json"
CLARITY_FILE = "clarity.json"
RECOMMINFO_FILE = "recomminfo.json"
GOOGLENEWS = "GoogleNews"
SUGG_GOOGLENEWS = "SuggGoogleNews"
GOOGLENEWS_JSON_FILE = "GoogleNews.json"
GOOGLE_LINKS_DIR ="Google_Links_Dir"
GOOGLE_NEWS_DIR ="Google_News_Dir"
GOOGLE_LINKS_FILE = "Google_Links_File"
BOILER_GOOGLE_NEWS_DIR = "Boiler_Google_News_Dir"
BOILER_DATA_DIR = "Boiler_Data_Dir"
FINAL_DIR = "Final_dir"
FEEDBACK_DIR = "Feedback_dir"
URL_DIR = "Url_dir"
ULTIMATE_FILE = "ultimate.json"
RECOMMENDATION_DIR ="Recommendation_Dir"
MAX_SMOOTHNESS_EDGE = 5
SMOOTHNESS_EDGE_WEIGHT = 2
MAX_CLARITY_EDGE = 5
CLARITY_EDGE_WEIGHT = 3
TYPE_HISTORY = "history"
TYPE_RECOMM = "recomm"
TYPE_TOPICS = "topics"
TYPE_NER = "ner"
TYPE_MAIN = "main"
NUM_SEED_NODES = 30
THRESHOLD_SEED_EDGE = 2
ALPHA_PARAM = 0.85
RECOMMENDED_LINKS = 40
LAST_GRAPH_RELEVANCE_DIR = "LAST_GRAPH_RELEVANCE_DIR"
LAST_GRAPH_SUGG_RELEVANCE_DIR = "LAST_GRAPH_SUGG_RELEVANCE_DIR"
LAST_GRAPHNER_RELEVANCE_DIR = "LAST_GRAPHNER_RELEVANCE_DIR"
LAST_GRAPHNER_SUGG_RELEVANCE_DIR = "LAST_GRAPHNER_SUGG_RELEVANCE_DIR"
LAST_GRAPH_SUGG_SMOOTHNESS_DIR = "LAST_GRAPH_SUGG_SMOOTHNESS_DIR"
LAST_GRAPH_SMOOTHNESS_DIR = "LAST_GRAPH_SMOOTHNESS_DIR"
LAST_GRAPHNER_SUGG_SMOOTHNESS_DIR = "LAST_GRAPHNER_SUGG_SMOOTHNESS_DIR"
LAST_GRAPHNER_SMOOTHNESS_DIR = "LAST_GRAPHNER_SMOOTHNESS_DIR"
LAST_GRAPH_SUGG_CLARITY_DIR = "LAST_GRAPH_SUGG_CLARITY_DIR"
LAST_GRAPH_CLARITY_DIR = "LAST_GRAPH_CLARITY_DIR"
LAST_GRAPHNER_SUGG_CLARITY_DIR = "LAST_GRAPHNER_SUGG_CLARITY_DIR"
LAST_GRAPHNER_CLARITY_DIR = "LAST_GRAPHNER_CLARITY_DIR"
LAST_GRAPH_RECOMM_DONE = "LAST_GRAPH_RECOMM_DONE"
LAST_GRAPHNER_RECOMM_DONE = "LAST_GRAPHNER_RECOMM_DONE"
GOOGLENEWS = "GoogleNews"
SUGG_GOOGLENEWS = "SuggGoogleNews"
TYPE_GOOGLE = "goo"
TYPE_SUGG = "sugg"
TRAINING_DAY = 5
MAX_FILES_SMOOTHNESS = 200
#TODAY = "11-15-2015"
#YESTERDAY = "11-14-2015"